version: 2
jobs:
  build:
    working_directory: ~/project/web
    environment:
      IMAGE_NAME: olvert/next-waves
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout:
          path: ~/project
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: main
