query postsByPagination($limit: Int!, $offset: Int!) {
  allPost(limit: $limit, offset: $offset, sort: { _createdAt: DESC }) {
    title,
    slug {
      current
    },
    body {
      ... on Image {
        _key,
        asset {
          url,
          metadata {
            dimensions {
              height,
              width,
            }
          }
        }
      }
      ... on Video {
        _key,
        videoId,
        isVimeo
      }
    },
    tags {
      title,
      slug {
        current
      }
    },
    publishedAt
  }
}