version: '3.5'

services:
  next-waves:
    container_name: next-waves
    image: olvert/next-waves
    environment:
      - VIRTUAL_HOST=dev.waves.olle.io
      - LETSENCRYPT_HOST=dev.waves.olle.io
    networks:
      - proxy-net
    restart: always

networks:
  proxy-net:
    external: 
      name: nginx-proxy
